name: trivago
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  flutter_riverpod: ^2.4.9
  data_class_plugin: any
  freezed_annotation: ^2.4.1
  fpdart: ^1.1.0
  routemaster: ^1.0.1
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  cr_calendar: ^1.2.1
  syncfusion_flutter_calendar: ^24.1.45
  date_time_format: ^2.0.1
  syncfusion_flutter_datepicker: ^24.1.45
  json_annotation: ^4.8.1
  freezed: ^2.4.6
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  collection: ^1.18.0
  get: ^4.6.6
  fl_chart: ^0.66.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: any
  tachyon: any
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
